version: '3'
services:
  next-js:
    #image: it for name your image after docker build -t nameyourimages .
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3520:3000